version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: backend:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json

      - ./.env:/opt/app/.env
      # - backend_uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - backendnetwork
    depends_on:
      - backendDB

  backendDB:
    container_name: backendDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - '54329:5432'
    networks:
      - backendnetwork
